// flow-typed signature: 628419837a7ce58585663f9fbda14316
// flow-typed version: <<STUB>>/@abandonware/noble_v^1.9.2-9/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@abandonware/noble'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@abandonware/noble' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@abandonware/noble/examples/advertisement-discovery' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/cache-gatt-discovery' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/cache-gatt-reconnect' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/echo' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/enter-exit' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/peripheral-explorer-async' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/peripheral-explorer' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/pizza/central' {
  declare module.exports: any;
}

declare module '@abandonware/noble/examples/pizza/pizza' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/characteristic' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/descriptor' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/distributed/bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/acl-stream' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/crypto' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/gap' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/gatt' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/hci' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/signaling' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/hci-socket/smp' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/mac/bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/noble' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/peripheral' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/resolve-bindings-web' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/resolve-bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/service' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/webbluetooth/bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/lib/websocket/bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test/test-characteristic' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test/test-descriptor' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test/test-noble' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test/test-peripheral' {
  declare module.exports: any;
}

declare module '@abandonware/noble/test/test-service' {
  declare module.exports: any;
}

declare module '@abandonware/noble/with-bindings' {
  declare module.exports: any;
}

declare module '@abandonware/noble/ws-slave' {
  declare module.exports: any;
}

// Filename aliases
declare module '@abandonware/noble/examples/advertisement-discovery.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/advertisement-discovery'>;
}
declare module '@abandonware/noble/examples/cache-gatt-discovery.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/cache-gatt-discovery'>;
}
declare module '@abandonware/noble/examples/cache-gatt-reconnect.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/cache-gatt-reconnect'>;
}
declare module '@abandonware/noble/examples/echo.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/echo'>;
}
declare module '@abandonware/noble/examples/enter-exit.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/enter-exit'>;
}
declare module '@abandonware/noble/examples/peripheral-explorer-async.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/peripheral-explorer-async'>;
}
declare module '@abandonware/noble/examples/peripheral-explorer.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/peripheral-explorer'>;
}
declare module '@abandonware/noble/examples/pizza/central.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/pizza/central'>;
}
declare module '@abandonware/noble/examples/pizza/pizza.js' {
  declare module.exports: $Exports<'@abandonware/noble/examples/pizza/pizza'>;
}
declare module '@abandonware/noble/index' {
  declare module.exports: $Exports<'@abandonware/noble'>;
}
declare module '@abandonware/noble/index.js' {
  declare module.exports: $Exports<'@abandonware/noble'>;
}
declare module '@abandonware/noble/lib/characteristic.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/characteristic'>;
}
declare module '@abandonware/noble/lib/descriptor.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/descriptor'>;
}
declare module '@abandonware/noble/lib/distributed/bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/distributed/bindings'>;
}
declare module '@abandonware/noble/lib/hci-socket/acl-stream.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/acl-stream'>;
}
declare module '@abandonware/noble/lib/hci-socket/bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/bindings'>;
}
declare module '@abandonware/noble/lib/hci-socket/crypto.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/crypto'>;
}
declare module '@abandonware/noble/lib/hci-socket/gap.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/gap'>;
}
declare module '@abandonware/noble/lib/hci-socket/gatt.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/gatt'>;
}
declare module '@abandonware/noble/lib/hci-socket/hci.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/hci'>;
}
declare module '@abandonware/noble/lib/hci-socket/signaling.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/signaling'>;
}
declare module '@abandonware/noble/lib/hci-socket/smp.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/hci-socket/smp'>;
}
declare module '@abandonware/noble/lib/mac/bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/mac/bindings'>;
}
declare module '@abandonware/noble/lib/noble.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/noble'>;
}
declare module '@abandonware/noble/lib/peripheral.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/peripheral'>;
}
declare module '@abandonware/noble/lib/resolve-bindings-web.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/resolve-bindings-web'>;
}
declare module '@abandonware/noble/lib/resolve-bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/resolve-bindings'>;
}
declare module '@abandonware/noble/lib/service.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/service'>;
}
declare module '@abandonware/noble/lib/webbluetooth/bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/webbluetooth/bindings'>;
}
declare module '@abandonware/noble/lib/websocket/bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/lib/websocket/bindings'>;
}
declare module '@abandonware/noble/test.js' {
  declare module.exports: $Exports<'@abandonware/noble/test'>;
}
declare module '@abandonware/noble/test/test-characteristic.js' {
  declare module.exports: $Exports<'@abandonware/noble/test/test-characteristic'>;
}
declare module '@abandonware/noble/test/test-descriptor.js' {
  declare module.exports: $Exports<'@abandonware/noble/test/test-descriptor'>;
}
declare module '@abandonware/noble/test/test-noble.js' {
  declare module.exports: $Exports<'@abandonware/noble/test/test-noble'>;
}
declare module '@abandonware/noble/test/test-peripheral.js' {
  declare module.exports: $Exports<'@abandonware/noble/test/test-peripheral'>;
}
declare module '@abandonware/noble/test/test-service.js' {
  declare module.exports: $Exports<'@abandonware/noble/test/test-service'>;
}
declare module '@abandonware/noble/with-bindings.js' {
  declare module.exports: $Exports<'@abandonware/noble/with-bindings'>;
}
declare module '@abandonware/noble/ws-slave.js' {
  declare module.exports: $Exports<'@abandonware/noble/ws-slave'>;
}
