// flow-typed signature: f11bd2f6ebde6bf08c84dc6f7e2a6f57
// flow-typed version: <<STUB>>/jbinary_v^2.1.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jbinary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jbinary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jbinary/dist/browser/jbinary' {
  declare module.exports: any;
}

declare module 'jbinary/dist/node/jbinary' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jbinary/dist/browser/jbinary.js' {
  declare module.exports: $Exports<'jbinary/dist/browser/jbinary'>;
}
declare module 'jbinary/dist/node/jbinary.js' {
  declare module.exports: $Exports<'jbinary/dist/node/jbinary'>;
}
