// flow-typed signature: 1319321c28ee483d1e381018c1bda446
// flow-typed version: <<STUB>>/node-aes-cmac_v^0.1.1/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-aes-cmac'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-aes-cmac' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-aes-cmac/lib/aes-cmac' {
  declare module.exports: any;
}

declare module 'node-aes-cmac/lib/buffer-tools' {
  declare module.exports: any;
}

declare module 'node-aes-cmac/test/aes-cmac' {
  declare module.exports: any;
}

declare module 'node-aes-cmac/test/buffer-tools' {
  declare module.exports: any;
}

declare module 'node-aes-cmac/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-aes-cmac/index' {
  declare module.exports: $Exports<'node-aes-cmac'>;
}
declare module 'node-aes-cmac/index.js' {
  declare module.exports: $Exports<'node-aes-cmac'>;
}
declare module 'node-aes-cmac/lib/aes-cmac.js' {
  declare module.exports: $Exports<'node-aes-cmac/lib/aes-cmac'>;
}
declare module 'node-aes-cmac/lib/buffer-tools.js' {
  declare module.exports: $Exports<'node-aes-cmac/lib/buffer-tools'>;
}
declare module 'node-aes-cmac/test/aes-cmac.js' {
  declare module.exports: $Exports<'node-aes-cmac/test/aes-cmac'>;
}
declare module 'node-aes-cmac/test/buffer-tools.js' {
  declare module.exports: $Exports<'node-aes-cmac/test/buffer-tools'>;
}
declare module 'node-aes-cmac/test/index' {
  declare module.exports: $Exports<'node-aes-cmac/test'>;
}
declare module 'node-aes-cmac/test/index.js' {
  declare module.exports: $Exports<'node-aes-cmac/test'>;
}
