// flow-typed signature: 2122ba933045ff7e4187f67a0149b291
// flow-typed version: <<STUB>>/serialport_v^9.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serialport/lib' {
  declare module.exports: any;
}

declare module 'serialport/lib/parsers' {
  declare module.exports: any;
}

declare module 'serialport/test' {
  declare module.exports: any;
}

declare module 'serialport/thank-you' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serialport/lib/index' {
  declare module.exports: $Exports<'serialport/lib'>;
}
declare module 'serialport/lib/index.js' {
  declare module.exports: $Exports<'serialport/lib'>;
}
declare module 'serialport/lib/parsers.js' {
  declare module.exports: $Exports<'serialport/lib/parsers'>;
}
declare module 'serialport/test.js' {
  declare module.exports: $Exports<'serialport/test'>;
}
declare module 'serialport/thank-you.js' {
  declare module.exports: $Exports<'serialport/thank-you'>;
}
