// flow-typed signature: fc6731a79bdd98bfaa5ab7830134ee50
// flow-typed version: <<STUB>>/@kabbi/aes-ccm_v^1.0.3/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kabbi/aes-ccm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kabbi/aes-ccm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@kabbi/aes-ccm/examples/decrypt' {
  declare module.exports: any;
}

declare module '@kabbi/aes-ccm/examples/encrypt' {
  declare module.exports: any;
}

declare module '@kabbi/aes-ccm/lib' {
  declare module.exports: any;
}

declare module '@kabbi/aes-ccm/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@kabbi/aes-ccm/examples/decrypt.js' {
  declare module.exports: $Exports<'@kabbi/aes-ccm/examples/decrypt'>;
}
declare module '@kabbi/aes-ccm/examples/encrypt.js' {
  declare module.exports: $Exports<'@kabbi/aes-ccm/examples/encrypt'>;
}
declare module '@kabbi/aes-ccm/lib/index' {
  declare module.exports: $Exports<'@kabbi/aes-ccm/lib'>;
}
declare module '@kabbi/aes-ccm/lib/index.js' {
  declare module.exports: $Exports<'@kabbi/aes-ccm/lib'>;
}
declare module '@kabbi/aes-ccm/test/test.js' {
  declare module.exports: $Exports<'@kabbi/aes-ccm/test/test'>;
}
