// flow-typed signature: 9638b3b296c03a7b356d1b724f374351
// flow-typed version: <<STUB>>/@serialport/parser-readline_v^9.0.0/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@serialport/parser-readline'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@serialport/parser-readline' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@serialport/parser-readline/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@serialport/parser-readline/lib/index' {
  declare module.exports: $Exports<'@serialport/parser-readline/lib'>;
}
declare module '@serialport/parser-readline/lib/index.js' {
  declare module.exports: $Exports<'@serialport/parser-readline/lib'>;
}
